### PR TITLE
pangram: Implemented new exercise

### PR DESCRIPTION
**Pull request by behrtam**
Example solution for new proposed exercise https://github.com/exercism/x-common/pull/133
Will be updated later based on possible feedback there.

### CODE REVIEW

**Comment by Dog** [comment]
Under what case is your set going to have a length over 26? (assuming ascii_letters)

Isn't this exercise region specific due to the use of isalpha? I don't know much about region differences, so I'm going to use German characters in my example only because I'm more familiar with the language.

My understanding of isalpha is it uses the constant string.letters to determine how it should return. If we switched to a "German" region, I'm worried ä, ö, ü, ß will also be included in the set because string.letters is region dependent. Since the size of string.letters changed, this means we could potentially substitute the letter z for the letter ä and still pass.

This raises a few questions: 

* Should a German pangram include  ä, ö, ü, ß?
* Should we consider limiting to ascii_letters?

**Comment by behrtam** [comment]
Good point! While the behaviour of the string method `isalpha()` doesn't change if you switch region or localisation, it still is a bad choice here. `'abcdefghijklmnopqrstuvwΣΩδ'` as input would return `true` while it clearly is missing `'xyz'`. We could use `? in ascii_lowercase` instead of `isalpha()`.
```python
>>> from string import ascii_lowercase
>>> pan = lambda s: len(set(char for char in s.lower() if char in ascii_lowercase)) == 26
>>> pan('abcdefghijklmnopqrstuvwxyz')
True
>>> pan('abcdefghijklmnopqrstuvwöüä')
False
>>>
```

**Comment by behrtam** [comment]
We could even get ride of the `len/set` combination. This is fare more readable.
```python
>>> pan = lambda s: all(char in s for char in ascii_lowercase)
>>> pan('abcdefghijklmnopqrstuvwΣΩδxyz')
True
>>> pan('abcdefghijklmnopqrstuvwΣΩδ')
False
>>>
```

**Comment by Dog** [comment]
I really like the solution with all

**Pull request merged**
