### PR TITLE
Peque

### PR DESCRIPTION
**Pull request by Peque**
Updated "simple-cipher" exercise to satisfy all the rules defined in the README file.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks! Would you mind squashing these commits, please?

**Comment by Peque** [comment]
If you would insist, I will, yes. :blush:

However, as stated in the [official Git documentation](https://git-scm.com/book/ch5-2.html):

> [...] try to make each commit a logically separate changeset [...] try to make your changes digestible [...] split your work into at least one commit per issue, with a useful message per commit [...] The project snapshot at the tip of the branch is identical whether you do one commit or five, as long as all the changes are added at some point, so try to make things easier on your fellow developers when they have to review your changes. This approach also makes it easier to pull out or revert one of the changesets if you need to later.

Each of those commits in the pull request do a different thing, which is well explained in the commit message. That way they are easier to understand, review and maybe revert in the future.

So, why would you prefer me to squash them into one? :sweat_smile:

**Comment by kytrinyx** [comment]
"a logically separate changeset" can mean different things at different levels of abstraction. Here I was looking at the entire PR as a global improvement to "simple-cipher".

If you do not wish to squash them, that's fine. In that case, please update the second and forth commit messages so that they mention which exercise they are changing.

**Comment by Peque** [comment]
@kytrinyx Sorry for that. Commit messages updated.

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
