### PR TITLE
Add word-search exercise

### PR DESCRIPTION
**Pull request by behrtam**
I don't really like the example solution, but it works. Also I'm not sure if it is the right way to provide the `class Point` this way.

https://github.com/exercism/x-common/blob/master/exercises/word-search/description.md

### CODE REVIEW

**Comment by patricksjackson** [comment]
I like providing the `Point` class. It could've been done with just having them return the coords as a tuple, but this way is more explicit.

LGTM 👍

**Comment by pheanex** [comment]
Hey @behrtam, I've got two questions on this:
* Since in #272 you were quite in favor of very minimal skeleton files, why did you provide such a (huge)  skeleton file here?
* Aren't we limiting the user by forcing the class-structure? (I do not see yet the added value of the "Point" class/general class structure)

**Comment by behrtam** [comment]
Well it's four months away, but I assume I did it that way because the test suit relies on the `class Point`. This is probably a unpleasant result of my example implementation which I normally write first.

Maybe if we would instead test with tuples that represent a point, we would not need a dedicated class for that, which also means we could reduce the skeleton file and the people solving this problem would have more freedom.

**Comment by pheanex** [comment]
Ah ok that makes sense, thank you.
If its okay with you, I'll try to refactor it a bit and send a PR :smile:

**Comment by pheanex** [comment]
Okay i created PR #420, please review.
Please note: I also changed the order of point tuples from coordinate-based (x,y) to a (at least to my mind) more intuitive (row,colum) notation. (If you prefer the coordinate-system, i'll update it).

**Pull request merged**
