### PR TITLE
house: more test

### PR DESCRIPTION
**Pull request by MartinDelille**
I also add a double \n at the end of the rhyme

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is failing CI, would you mind taking a look?

I've been removing the double "\n" at the end of long texts, on the logic that when I write in text files I don't keep a blank line at the end.

**Comment by MartinDelille** [comment]
ok no problem. Since I had a "verse" function import the test is failing. I'm looking at the .`travis.yml`  and the `check_exercises.py` scripts but I can figure where are the files that are test by the spec?

**Comment by kytrinyx** [comment]
The test runs against the reference solution (example.py)

**Comment by MartinDelille** [comment]
Travis is ok and I removed the double \n. I had to rename `_verse()` to `verse()` in _example.py_ to fix the error. Do you want me to squash the commit?

**Comment by kytrinyx** [comment]
Yeah, if you wouldn't mind squashing the commit, that would be great, thanks!

**Comment by MartinDelille** [comment]
hi @kytrinyx ! What about my PR? Tell me if you think there is a problem about it!

**Comment by kytrinyx** [comment]
Hi @MartinDelille GitHub doesn't notify me when a PR is updated, only when there's a new comment. I never saw this. I'm so sorry!

**Comment by MartinDelille** [comment]
Ok no problem! :+1:

**Pull request merged**
