### PR TITLE
Added Python 3.6 in travis

### PR DESCRIPTION
**Pull request by surajnarwade**

### CODE REVIEW

**Comment by surajnarwade** [comment]
Oh it seems travis-ci do not support python 3.6, but I checked with docs, it tells me to add 'nightly' which points to '3.6-dev', should I add that ?

**Comment by surajnarwade** [comment]
Fixes #364

**Comment by kytrinyx** [comment]
Oh, sweet!

Should we allow the build to fail against `nightly`, @behrtam? Or merge as is, and if it becomes a problem we can adjust it.

**Comment by patricksjackson** [comment]
Python 3.6 is still in beta. I expect that @behrtam wanted to add it once it is actually released rather than pointing at `nightly`, which is Pythons active development branch.

Using that is very different from adding a new version of Python to test against.

**Comment by behrtam** [comment]
I mixed up the release of the beta 1 (the end of the feature development phase) with the actual final version. But adding the nightly to know where we stand does sound like a good idea.

```
matrix:
    allow_failures:
        - python: "nightly"
```

**Comment by surajnarwade** [comment]
should I sent new patch or this is going to be closed :( ?

**Comment by behrtam** [comment]
You can just update this PR.

**Pull request merged**
