### PR TITLE
Broaden tests in ocr-numbers exercise.

### PR DESCRIPTION
**Pull request by cjchallis**

### CODE REVIEW

**Comment by sjakobi** [comment]
That's a much more encompassing test suite now, but it seems that you're basically giving away the solution for the `grid` function with `join_ocr` in `ocr_test.py`.

I believe it would be better if the test cases would simply compare the output of the `number` and `grid` functions with literals or at least short expressions that are easy to grasp.

**Comment by cjchallis** [comment]
Fair point. I'll use the functions to create some literals to test again and then remove the functions.

**Comment by cjchallis** [comment]
Same tests, updated to use literals instead of functions.

**Comment by sjakobi** [comment]
Thanks! That's a great test suite and I'm willing to merge it.

However, there's another improvement possible, which would be to move the "number grids" directly into the respective test methods. That way everything I need to know about a test case is defined right inside the test case and I don't have to look up a constant defined elsewhere.

If you don't want to make that change for any reason, never mind, I'll merge your PR anyways. But I think that this test suite could be even better!

**Comment by cjchallis** [comment]
My only reservation with this is that most of the grids are used to test both `numbers` and `grid`, so it makes sense to define them once and then use in both.  I'll go make the change, however, if you still think they should belong in each test case.

**Comment by sjakobi** [comment]
> My only reservation with this is that most of the grids are used to test both numbers and grid, so it makes sense to define them once and then use in both.

:blush: - I guess I actually overlooked that…

Ok, do as you please. There's a tradeoff of redundancy and locality/simplicity here and I don't see any clear guidelines on how to approach it.

**Comment by cjchallis** [comment]
I changed all of the literals to be in-line with the tests.  I think it is cleaner this way, but in several tests I defined an auixiliary variable `digits` solely to keep the same format among tests without exceeding 79 characters in a line.

**Comment by sjakobi** [comment]
:+1:

**Pull request merged**
