### PR TITLE
rectangles: converted exercice from Rust track

### PR DESCRIPTION
**Pull request by tuxication**

### CODE REVIEW

**Comment by tuxication** [comment]
I'm not sure what the problem with the checks.. I can modify the code with some help:)

**Comment by kytrinyx** [comment]
It passes in python 2.x but fails in python 3.x -- unfortunately I don't know enough python to guess at what bits of syntax are the culprits here.

**Comment by Dog** [comment]
This shows as passing for me. I'll try to merge it later today and will manually double check it.

**Comment by Dog** [comment]
Thanks. Sorry it took so long to merge.

**Pull request merged**
