### PR TITLE
Move the clock exercise later in fetch order

### PR DESCRIPTION
**Pull request by cmlang42**
- moves the clock exercise later (down) in the exercise suite

### CODE REVIEW

**Comment by behrtam** [comment]
Great first step on the way to improve the `clock` exercise. Could you rewrite your commit message to follow the mentioned format from the [README](https://github.com/exercism/xpython#pull-requests) and so that it states what actually is done and not just copy-paste the issue title.

**Comment by cmlang42** [comment]
@behrtam thanks for the feedback, made changes to the commit message. I added more detail there.

**Comment by behrtam** [comment]
It is convention to prefix the commit message with the exercise name: https://github.com/exercism/xpython#pull-requests

So, if could change it again we might be able to merge this right away.

**Comment by cmlang42** [comment]
@behrtam done. The CI operations are running now

**Comment by behrtam** [comment]
Thanks, for your work!

**Comment by cmlang42** [comment]
Welcome. Enjoyed being a part of the project. I will keep involved.

**Pull request merged**
