### PR TITLE
Clock: remove duplicated tests

### PR DESCRIPTION
**Pull request by rootulp**
These four tests are repeated immediately above

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice find!

CI has an odd failure on this one, saying that an equality test fails. Do you have a moment to look into it? It seems weird that it would be related to this change.

**Comment by rootulp** [comment]
Turns out the second iteration of test_clocks_with_hour_overflow overwrote the first one. There was a discrepancy between testing for equality and inequality. I made the fix!

**Comment by kytrinyx** [comment]
Sweet, thanks so much!

**Comment by kytrinyx** [comment]
@Dog I'm going to go ahead and merge this one.

**Pull request merged**
