### PR TITLE
word-count: 'javascript!!&@$%^&' should be not accepted as a word

### PR DESCRIPTION
**Pull request by ghajba**
I did this exercise today while commuting to work and I think this solution was a bad-bad thing so I altered the test case and the example to handle this issue. If you do not think alike I understand.
Cheers, Gabor

### CODE REVIEW

**Comment by etrepum** [comment]
I like having it require the split condition be anything that's not alphanumeric, it requires a little more digging than a whitespace split which is usually some sort of built-in method or function in most languages.

In Haskell we use the unicode definition of alphanumeric. This Python implementation looks like it's just ASCII. In Python that would be tricky (but possible) to do with a regex because the `\w` class includes underscore but the spec for this exercise does not.

```python
import re

def word_count(text):
    d = {}
    # use a negative lookahead assertion to remove underscore from \w
    for word in re.findall(r'(?:(?!_)\w)+(?u)', text):
        d[word] = d.get(word, 0) + 1
    return d
```

Simpler solution would do two passes to handle the underscore case:

```python
import re

def word_count(text):
    d = {}
    for word in re.findall(r'\w+', text.replace('_', ' ')):
        d[word] = d.get(word, 0) + 1
    return d
```

`re.split` is more awkward to use because then you have to deal with empty strings.

**Comment by ghajba** [comment]
If I may leave another comment: in the Java version of the same exercise special characters (like colon or this awkward javascript-extension) aren't permitted in the solution.

And I have to agree with @etrepum the current solution does not handle non-ascii characters. However the solution does not necessary have to be done with regular expressions, does it?

**Comment by etrepum** [comment]
Regex is certainly not a necessity, I was just modifying the existing proposed solution to make it work with the full spec that the Haskell version implements. Here's one way to do it in a fairly low-level fashion:

```python
def word_count(text):
    i = 0
    end = len(text)
    d = {}
    while i < end:
        while i < end and not text[i].isalnum():
            i = i + 1
        j = i
        while j < end and text[j].isalnum():
            j = j + 1
        if j > i:
            word = text[i:j]
            d[word] = d.get(word, 0) + 1
        i = j
    return d
```

**Comment by Dog** [comment]
I'm in favor of doing it the Haskell way, and performing a split if its not alphanumeric.

**Comment by behrtam** [comment]
* The proposed implementation does not normalize (#207) and does not support unicode.
* I would suggest that we create a different pr for the unicode test, because it might need some more work to support Python 2 & 3.
* As we switch to the haskell way of splitting we should also add their test case for symbols.
```haskell
testCase "symbols are separators" $
    fromList [("hey", 1), ("my", 1), ("spacebar", 1),
              ("is", 1), ("broken", 1)] @=?
    wordCount "hey,my_spacebar_is_broken."
```

**Comment by kytrinyx** [comment]
+1 for adding the haskell test case.

Let's do as you suggest and put the unicode test in a different PR.

**Comment by behrtam** [comment]
As @ghajba seems to have no time or interest in finishing this here and the example code doesn't work at all for the new way of splitting. Should we close this and reopen a new pr or merge this to a branch and refactor/fix it there?

**Comment by kytrinyx** [comment]
Yeah, I think that's fine. Thanks, @behrtam.

**Pull request closed without merging**
