### PR TITLE
allergies: Comment-out bitwise-specific test

### PR DESCRIPTION
**Pull request by ZacharyRSmith**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you!

**Comment by Dog** [comment]
This should've had the test skipped, not commented out.

**Comment by kytrinyx** [comment]
Would you mind making the change, @Dog?

**Comment by Dog** [comment]
Sure, I can do that.

**Comment by Dog** [comment]
Pushed in https://github.com/exercism/xpython/pull/209

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
