### PR TITLE
sieve has fencepost problems and no test to detect it

### PR DESCRIPTION
**Pull request by AlexMooney**
As per the failing pull request [157](https://github.com/exercism/xpython/pull/157), the unit tests for the `sieve.py` program do not test that you include the final prime number if your upper limit happens to be prime.  I've added a test for `sieve(7)` as well as correcting the `example.py` to correctly compute `sieve(7)`.

### CODE REVIEW

**Comment by sjakobi** [comment]
Thanks for clarifying the test suite!

Could you now please squash your two commits into one (see the paragraph on "Squashing" [here](http://help.exercism.io/git-workflow.html)) and write the first line of your commit message in the style `sieve: <Short description>`?

Cheers!

**Comment by sjakobi** [comment]
Thanks, @AlexMooney!

**Comment by Dog** [comment]
While the README wasn't clear, this seemed to be more of an inclusive versus exclusive issue.

If I'm not mistaken the problem was originally exclusive and the problem was just made to be inclusive. It doesn't actually matter which way its implemented, we just need to be explicit about which way we want it to work in the README.

**Comment by kytrinyx** [comment]
Yeah the READMEs are shared between languages.

I don't think we've had any conversations about `[2, max)` vs `[2, max]` anywhere.

**Pull request merged**
