### PR TITLE
README: Some advice for contributors

### PR DESCRIPTION
**Pull request by sjakobi**
Closes https://github.com/exercism/xpython/issues/150

### CODE REVIEW

**Comment by sjakobi** [comment]
I fear that I may have chosen an overly patronizing or demanding tone.

Should I change something else?

**Comment by Dog** [comment]
I think the tone is fine, but I left a comment regarding the single tests.

To make it a bit less intimidating, perhaps add a line that mentions its okay to make mistakes, but they should try to turn them into learning experiences. I'd plug that they can ask questions on IRC.

**Comment by kytrinyx** [comment]
Another idea I came across today was to encourage people to contribute by _making the README work for you_. If something is unclear, or if you get stuck, or if you discover that it's different on your system, then open issues to ask questions and submit a pull request that explains how to make it work on your system.

**Comment by kytrinyx** [comment]
I'm going to go ahead and merge this. If there are improvements to be made, please open a new PR :)

**Pull request merged**
