### PR TITLE
Remove old help site links

### PR DESCRIPTION
**Pull request by kotp**
Still needs the new reference for git workflow introduction.

references #323

### CODE REVIEW

**Comment by kytrinyx** [comment]
> Still needs the new reference for git workflow introduction.

Where?

Does this cover it? https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#git-basics

**Comment by kotp** [comment]
I believe it does.   Should we link directly there or is this reflected on the website somewhere?

https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#write-some-code is another one I found.

Unsure which to use as a link though.

As to where am I referencing the need?  It is actually in the README.md file, not (yet) included in this pull request.

The old link was http://help.exercism.io/git-workflow.html and I was hoping for one that was http://exercism.io/contributing.html#git-workflow perhaps, or if specific to a language, then exercism.io/python/contributing.html#git-workflow.html maybe.

**Comment by kytrinyx** [comment]
Yeah, for now let's link to the Contributing guide on x-common as you've done here.

Thanks!

**Comment by kotp** [comment]
Sounds good.  I would have squashed the commits, but this will work. :)

Thanks @kytrinyx

**Comment by kytrinyx** [comment]
I squashed the commits with the new button; just wanted to try it out :)

**Comment by kotp** [comment]
Awww... I wanted to!  It's all good.  Not like I won't get another chance to.

**Pull request merged**
