### PR TITLE
setup.md: Add hyperlink to exercism.io help page

### PR DESCRIPTION
**Pull request by bordeltabernacle**

### CODE REVIEW

**Comment by behrtam** [comment]
I would change the wording slightly from `information about the Python track` to `information about running tests, code style and linting`. This way you get a better feeling what you can expect behind the link.

**Comment by bordeltabernacle** [comment]
Ok, I've added the changes, but I'm not sure if I've messed up the Git workflow? (I'm a lone dev and haven't had a lot of experience with Git across a team!).  Apologies if I've messed this up, I can open a new PR if that's easier?

**Comment by behrtam** [comment]
I'm also not a git expert. Maybe someone else can comment whether squashing with rebase, --amend or something like that can work it's magic here.

**Comment by kytrinyx** [comment]
Since the changes are about the same thing, I would tend to squash them.

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by bordeltabernacle** [comment]
Ok, cool, I think that should be it! Thanks for the link @kytrinyx

**Comment by Dog** [comment]
Merged in https://github.com/exercism/xpython/commit/6eeefa518e0ce12d72ad8ef8635129369dd15643

Thanks

**Comment by bordeltabernacle** [comment]
:+1: :smiley:

**Pull request merged**
