### PR TITLE
hello-world: Fix Hello World test class name & update test

### PR DESCRIPTION
**Pull request by bordeltabernacle**
Fix test class name to reflect exercise name.
Update tests to reflect Hello World metadata in x-common.

### CODE REVIEW

**Comment by behrtam** [comment]
That mistake looks like copy&paste. Could you rename the commit message to fit the proposed style from the README. https://github.com/exercism/xpython#pull-requests

**Comment by bordeltabernacle** [comment]
I thought that might have been the case.  Commit message renamed.

**Comment by Dog** [comment]
Thanks

**Comment by bordeltabernacle** [comment]
Cool. Thankyou!

**Pull request merged**
