### PR TITLE
Add a unit test for python minesweeper

### PR DESCRIPTION
**Pull request by RryLee**
I think should add this test.

    +-----+
        * |
    +-----+

this is invalid

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks, @RryLee!

@betegelse You implemented this exercise originally; would you have time to review this change?

**Comment by betegelse** [comment]
Sure, give me a couple of days

**Comment by behrtam** [comment]
Do you need any help?

**Comment by RryLee** [comment]
@behrtam I dont't see the offical solution, just completed it and found this flaw

**Comment by behrtam** [comment]
So the actual example implementation already works for this proposed new test case. The existing test case `test_faulty_border` does basically the same check, just with a different incorrect character. That's why I don't see any reason to add this.

**Pull request closed without merging**
