### PR TITLE
Update grade_school_test.py

### PR DESCRIPTION
**Pull request by de2Zotjes**
Changed the tests to minimize the restrictions on implementation.

Ref Issue #322

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is failing on Python 3.x. Would you mind taking a look?

**Comment by behrtam** [comment]
The method `assertItemsEqual ` is named `assertCountEqual` in Python3. [[see docs]](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual)

As the order in witch the names are added does matter in this exercise I would suggest to stay with `assertEqual`.

Could you change your commit message to match the style described in the [readme](https://github.com/exercism/xpython#pull-requests).

**Comment by de2Zotjes** [comment]
So I did something ugly to make this test work for 2.7 and 3.5 :)

As to the ordering being important I do not read that in the exercise readme. There is a sorted output where ordering is (ofcourse) important, but I took that as an indication that at other moments ordering is free/optional.
using the assertEqual operation gives rise to added restrictions on the return type of the data. A list won't equal a tuple, whereas the assertCountEqual considers both list and tuples as sets of data with counts of data.

**Comment by behrtam** [comment]
Had just done the Scala version of this exercise where they test on the initial add-order but I agree the description doesn't mention it.
It's a bit ugly but I don't see a better why of supporting version 2 and 3.

If you could adjust the commit message to the form `exercise-name: Add some things` I can merge this PR.

**Comment by de2Zotjes** [comment]
Last commit message is clean :)

**Pull request merged**
