### PR TITLE
binary-search implemented.

### PR DESCRIPTION
**Pull request by michaelkunc**

### CODE REVIEW

**Comment by patricksjackson** [comment]
If you were still planning on completing this, it's only failing the check because of formatting ...

**Comment by kytrinyx** [comment]
If we don't hear back from @michaelkunc, let's carry this one (see Jessie Frazelle's The Art of Closing](https://blog.jessfraz.com/post/the-art-of-closing/), section 4, _The Carry_).

**Comment by michaelkunc** [comment]
I should be able to fix this over the weekend. Thanks all.

**Comment by kytrinyx** [comment]
Awesome, thanks! :heart:

**Comment by kytrinyx** [comment]
Thank you so much @michaelkunc! I've merged it in 668631565f68095686dc2dd8cfb58f5973282f96

**Pull request closed without merging**
