### PR TITLE
Add exercise transpose

### PR DESCRIPTION
**Pull request by nithin-vijayan**
[WOI]  I will implement exercise transpose problem in python.

### CODE REVIEW

**Comment by behrtam** [comment]
Your commits don't contain any changes, maybe you forgot to stage the files before you created  the commits? `git add <file>`

**Comment by nithin-vijayan** [comment]
It was a work in progress pull request. Will implement and push the test files soon

**Comment by behrtam** [comment]
Sorry, because of the two commits with different authors I assumed you might have problems using git.

**Comment by behrtam** [comment]
I assume you moved your work to a new PR #459

**Comment by nithin-vijayan** [comment]
yes , . Thanks

**Pull request closed without merging**
