### PR TITLE
Poker : new exercises

### PR DESCRIPTION
**Pull request by MartinDelille**
I submitted a new exercise about ranking between different poker hand. I wrote a part of the example code with the help of this course: https://www.udacity.com/course/viewer#!/c-cs212/l-48688918

Is there anything to do to add it to the exercises list?

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yepp, we're going to need the metadata here: https://github.com/exercism/x-common

And then it needs to be added to the `config.json` problems list.

Thanks!

**Comment by MartinDelille** [comment]
Done

**Comment by MartinDelille** [comment]
@kytrinyx And what about this one?

**Comment by kytrinyx** [comment]
All good, thanks.

**Pull request merged**
