### PR TITLE
largest-series-product corner cases

### PR DESCRIPTION
**Pull request by petertseng**
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.

### CODE REVIEW

**Comment by petertseng** [comment]
Interesting that the CI is failing. The flake failures are files untouched by me. I ran tests locally and this worked, but would CI be working for anyone right now?

**Comment by petertseng** [comment]
Seems unlikely. flake8 hasn't changed either at https://gitlab.com/pycqa/flake8/commits/master . So I am stumped.

**Comment by petertseng** [comment]
Tested an empty commit on master. [That also fails](https://travis-ci.org/exercism/xpython/builds/104409101). Guess we gotta get those fixed up. I really do wonder what changed...

**Comment by petertseng** [comment]
Rebased on master. Should be fine now.

**Comment by behrtam** [comment]
Looks good. Thanks for your effort.

**Pull request merged**
