### PR TITLE
Add additional information to SETUP.md

### PR DESCRIPTION
**Pull request by bordeltabernacle**
Add information on running tests, and update submitting exercises
information so all example filenames are the same.  Also add link
to Python specific help pages on Exercism.io

### CODE REVIEW

**Comment by behrtam** [comment]
Running tests is already described in great detail in [WORKFLOW.md](https://github.com/exercism/xpython/blob/master/docs/WORKFLOW.md). I think it should only be explained in one place.

**Comment by bordeltabernacle** [comment]
I submitted this in response to what @kytrinyx said [here](https://github.com/exercism/exercism.io/issues/2198) and [here](https://github.com/exercism/xelixir/issues/37) regarding the `SETUP.md` containing basic info about running tests and linking to help.
But, tbh, I'm easy, whatever you think best. :smile:

**Comment by behrtam** [comment]
The `WORKFLOW.md` seams to be used for http://help.exercism.io which is referenced in the `SETUP.md`. I don't know where people start to look for help first or if it's better to have a short README with links or a long README and the help pages.

Personally I like the LISP way: https://github.com/exercism/xlisp/blob/master/SETUP.md

**Comment by kytrinyx** [comment]
I'm going to be using the stuff under `docs/` to add the "help" stuff to the languages section of the website. The `SETUP.md` gets included into the README, and I think it's very useful to have it there, since that would mean that people who already have python installed might never need to go to the help documentation on the site.

**Comment by Dog** [comment]
I think it may be better for us to provide a link to the testing documentation in our setup. I'm a bit worried about giving too much information.

**Comment by kytrinyx** [comment]
That sounds good to me.

**Comment by Dog** [comment]
@bordeltabernacle Would you like to submit that change, or would you like for @behrtam or I to do it?

**Comment by bordeltabernacle** [comment]
Ok, grand, I'd be very happy to submit the change. Thankyou.

**Comment by bordeltabernacle** [comment]
Is this something that's going to be unified across the languages?  Maybe a template/stylesheet/guide describing what info is where?

**Comment by bordeltabernacle** [comment]
I don't think I've managed to control Git in the proper manner! If it's not Emacs biting me in the ass, it's Git! Anyway, the new PR is [here](https://github.com/exercism/xpython/pull/250).

**Comment by kytrinyx** [comment]
@bordeltabernacle I'm not sure it's going to be unified--it really depends on the language what information is useful.

**Pull request closed without merging**
